### ISSUE TITLE
We can´t use it with Arduino 1.0 core

### ISSUE THREAD

**Issue by GoogleCodeExporter** [carlosdelfino/agentuino#2]
```
Can´t compile using Arduino 1.0

Errors:
\arduino-1.0\libraries\Agentuino\Agentuino.cpp: In member function 
'SNMP_API_STAT_CODES AgentuinoClass::begin()':
\arduino-1.0\libraries\Agentuino\Agentuino.cpp:39: error: 'Udp' was not 
declared in this scope
\arduino-1.0\libraries\Agentuino\Agentuino.cpp: In member function 
'SNMP_API_STAT_CODES AgentuinoClass::begin(char*, char*, uint16_t)':
\arduino-1.0\libraries\Agentuino\Agentuino.cpp:63: error: 'Udp' was not 
declared in this scope
\arduino-1.0\libraries\Agentuino\Agentuino.cpp: In member function 'void 
AgentuinoClass::listen()':
\arduino-1.0\libraries\Agentuino\Agentuino.cpp:73: error: 'Udp' was not 
declared in this scope
\arduino-1.0\libraries\Agentuino\Agentuino.cpp: In member function 
'SNMP_API_STAT_CODES AgentuinoClass::requestPdu(SNMP_PDU*)':
\arduino-1.0\libraries\Agentuino\Agentuino.cpp:98: error: 'Udp' was not 
declared in this scope
\arduino-1.0\libraries\Agentuino\Agentuino.cpp: In member function 
'SNMP_API_STAT_CODES AgentuinoClass::responsePdu(SNMP_PDU*)':
\arduino-1.0\libraries\Agentuino\Agentuino.cpp:350: error: 'Udp' was not 
declared in this scope
```

Original issue reported on code.google.com by `portill...@gmail.com` on 19 Dec 2011 at 8:20
